config/routes.rb
Rails.application.routes.draw do

    root to: redirect('/admin/assignments')

    namespace :admin do
        get "assignments/generate" => "assignments#generate"
        resources :assignments
        resources :delivery_zones
        resources :restaurants do
            resources :meals
            resources :restrict_restaurant_days
            resources :restrict_restaurant_delivery_zones
        end
    end

    namespace :v1 do
        resources :assignments, only: [:index], defaults: { format: :json }
    end
end

app/models/restaurant.rb
##
# This class represents a Restaurant
#
# == Schema Information
#
# Table name: restaurants
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  api_key    :uuid
#

class Restaurant < ApplicationRecord
    has_many :meals, dependent: :destroy
    has_many :assignments
    has_many :delivery_zones, through: :assignments
    has_many :restrict_restaurant_delivery_zones, dependent: :destroy
    has_many :restrict_restaurant_days, dependent: :destroy
    before_create :generate_api_key
    after_destroy :destroy_future_assignments

    ##
    # Returns restaurants ordered by those with the last amount of historical delivery assignments ascending, while also
    # filtering out specific ones based on biz rules
    # Params:
    # delivery_zone_id: The ID of delivery zone to sort number of assignments to by
    # day: The day for which the assignment is going to be for
    #   Restaurant.find_least_assigned_available(delivery_zone_id, Date.today)
    def self.find_least_assigned_available(delivery_zone_id, day)
        least_assigned = self
            .find_least_assigned(delivery_zone_id)
            .having("sum(case when assignments.date = '#{day}' THEN 1 ELSE 0 end) < 3") # Having less than 3 delivery zones in the same day
            .having("sum(case when assignments.delivery_zone_id = #{delivery_zone_id} THEN 1 ELSE 0 end) < 1") # Having not already delivered to this delivery zone
        least_assigned = least_assigned.where('restaurants.id not in (?)', self.restricted_ids(delivery_zone_id, day)) unless self.restricted_ids(delivery_zone_id, day).blank?
        least_assigned.first
    end

    private 

    ##
    # Destroys only the assignments in the future
    def destroy_future_assignments
        self.assignments.in_the_future.destroy_all
    end

    ##
    # Generates the unique API key for the restaurant
    def generate_api_key
        begin
            self.api_key = SecureRandom.uuid
        end while Restaurant.exists?(api_key: api_key)
    end

    ##
    # Returns the IDs of restaurants that are restricted from delivering to the input zone and on the input day
    # Params:
    # delivery_zone_id: The ID of delivery zone to sort number of assignments to by
    # day: The day for which the assignment is going to be for
    #   self.restrict_ids(delivery_zone_id, Date.today)
    def self.restricted_ids(delivery_zone_id, day)
        restrict_ids = RestrictRestaurantDay.where(day: day.wday).pluck(:restaurant_id)
        restrict_ids.concat RestrictRestaurantDeliveryZone.where(delivery_zone_id: delivery_zone_id).pluck(:restaurant_id)
        restrict_ids
    end

    ##
    # Returns restaurants ordered by those with the least amount of historical delivery assignements to the input zone ascending
    # Params:
    # delivery_zone_id: The ID of delivery zone to sort number of assignments to by
    #   self.find_least_assigned(delivery_zone)
    def self.find_least_assigned(delivery_zone_id)
        Restaurant.select("restaurants.id, 
            sum(CASE WHEN assignments.delivery_zone_id = #{delivery_zone_id} THEN 1 ELSE 0 end) AS assignment_count")
            .left_joins(:assignments)
            .group(:id).order('COUNT(assignments.id) asc, assignment_count asc, restaurants.created_at asc')
    end
    
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController

    def new
        @restaurant = Restaurant.new    
    end

    def create
        @restaurant = Restaurant.new(restaurant_params)
        if @restaurant.save
            redirect_to admin_restaurants_url
        else
            render 'new'
        end
    end

    def index
        @restaurants = Restaurant.all.order(:name)
    end
  
    def show
        @restaurant = Restaurant.find(params[:id])
        redirect_to admin_restaurants_url if @restaurant.nil?
    end

    def edit
        @restaurant = Restaurant.find(params[:id])
        redirect_to admin_restaurants_url if @restaurant.nil?
    end

    def update
        @restaurant = Restaurant.find(params[:id])
        if @restaurant.update_attributes(restaurant_params)
            render 'show'
        else
            render 'edit'
        end
    end

    def destroy
        Restaurant.find(params[:id]).destroy
        flash[:success] = "Restaurant deleted"
        redirect_to admin_restaurants_url
    end

    private

    def restaurant_params
        params.require(:restaurant).permit(:name)
    end
end
  

app/views/admin/restaurants/edit.haml
%h1.text-center Edit Restaurant

= form_for @restaurant, url: {:action => "update", :id => @restaurant}, html: { method: :put } do |f|
  %p
    = f.label :name
    = f.text_field :name, class: 'form-control'
  %p
    = f.submit "Save", class: 'btn btn-primary'
    = link_to("Cancel", admin_restaurant_path(@restaurant), class: "btn btn-default text-black")

app/views/admin/restaurants/index.haml
%h1.text-center Restaurants
.table-container
  %table.table.table-condensed.borderless
    %thead
      %tr
        %th ID
        %th Name
    %tbody
      - @restaurants.each_with_index do |restaurant, index|
        %tr
          %td= restaurant.id
          %td= link_to(restaurant.name, admin_restaurant_path(restaurant.id))

= link_to("Add Restaurant", new_admin_restaurant_path, class: "btn btn-success text-white")

app/views/admin/restaurants/new.haml
%h1.text-center New Restaurant

= form_for @restaurant, url: {:action => "create"}, html: { method: :post } do |f|
  %p
    = f.label :name
    = f.text_field :name, class: 'form-control'
  %p
    = f.submit "Create", class: 'btn btn-primary'

app/views/admin/restaurants/show.haml
%h1.text-center Restaurant

%h2= @restaurant.name

%hr

%h2 Meals

- if @restaurant.meals.any?
  .table-container
    %table.table.table-condensed.borderless
      %thead
        %tr
          %th ID
          %th Name
      %tbody
        - @restaurant.meals.order(:name).each_with_index do |meal, index|
          %tr
            %td= meal.id
            %td= link_to(meal.name, admin_restaurant_meal_path(meal.id))

%p
  = link_to("Add Meal", new_admin_restaurant_meal_path(@restaurant), class: "btn btn-success text-white")

%hr

%h2 Delivery Restrictions

%h3 Restrcted Delivery Zones
- if @restaurant.restrict_restaurant_delivery_zones.any?
  .table-container
    %table.table.table-condensed.borderless
      %thead
        %tr
          %th ID
          %th Name
          %th 
      %tbody
        - @restaurant.restrict_restaurant_delivery_zones.each_with_index do |restricted_delivery_zone, index|
          %tr
            %td= restricted_delivery_zone.id
            %td= restricted_delivery_zone.delivery_zone.name
            %td= link_to("Remove", admin_restaurant_restrict_restaurant_delivery_zone_path(@restaurant.id, restricted_delivery_zone), method: :delete, class: "btn btn-danger text-white", data: { confirm: "Are you sure you wish to remove this restriction?" })

%p
  = link_to("Add Restricted Delivery Zone", new_admin_restaurant_restrict_restaurant_delivery_zone_path(@restaurant), class: "btn btn-success text-white")

%h3 Restrcted Weekdays
- if @restaurant.restrict_restaurant_days.any?
  .table-container
    %table.table.table-condensed.borderless
      %thead
        %tr
          %th ID
          %th Name
          %th
      %tbody
        - @restaurant.restrict_restaurant_days.each_with_index do |restricted_day, index|
          %tr
            %td= restricted_day.id
            %td= restricted_day.day.capitalize
            %td= link_to("Remove", admin_restaurant_restrict_restaurant_day_path(@restaurant.id, restricted_day), method: :delete, class: "btn btn-danger text-white", data: { confirm: "Are you sure you wish to remove this restriction?" })
%p
  = link_to("Add Restricted Delivery Weekday", new_admin_restaurant_restrict_restaurant_day_path(@restaurant), class: "btn btn-success text-white")

%hr

= link_to("Edit #{@restaurant.name}", edit_admin_restaurant_path(@restaurant.id), class: "btn btn-info text-white")

= link_to("Delete #{@restaurant.name}", admin_restaurant_path(@restaurant.id), method: :delete, class: "btn btn-danger text-white", data: { confirm: "Are you sure you wish to delete?" })

= link_to("All Restaurants", admin_restaurants_path, class: "float-right")