config/routes.rb
Rails.application.routes.draw do

    root to: redirect('/admin/assignments')

    namespace :admin do
        get "assignments/generate" => "assignments#generate"
        resources :assignments
        resources :delivery_zones
        resources :restaurants do
            resources :meals
            resources :restrict_restaurant_days
            resources :restrict_restaurant_delivery_zones
        end
    end

    namespace :v1 do
        resources :assignments, only: [:index], defaults: { format: :json }
    end
end

app/models/delivery_zone.rb
##
# This class represents a delivery zone
#
# == Schema Information
#
# Table name: delivery_zones
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class DeliveryZone < ApplicationRecord
    has_many :assignments
    has_many :restaurants, through: :assignments
    after_destroy :destroy_future_assignments

    private 

    ##
    # Destroys only the assignments in the future
    def destroy_future_assignments
        self.assignments.in_the_future.destroy_all
    end

end

app/controllers/admin/delivery_zones_controller.rb
class Admin::DeliveryZonesController < ApplicationController

    def new
        @delivery_zone = DeliveryZone.new    
    end

    def create
        @delivery_zone = DeliveryZone.new(delivery_zone_params)
        if @delivery_zone.save
            redirect_to admin_delivery_zones_url
        else
            render 'new'
        end
    end

    def index
        @delivery_zones = DeliveryZone.all.order(:name)
    end
  
    def show
        @delivery_zone = DeliveryZone.find(params[:id])
    end

    def edit
        @delivery_zone = DeliveryZone.find(params[:id])
        redirect_to admin_restaurants_url if @delivery_zone.nil?
    end

    def update
        @delivery_zone = DeliveryZone.find(params[:id])
        if @delivery_zone.update_attributes(delivery_zone_params)
            render 'show'
        else
            render 'edit'
        end
    end

    def destroy
        DeliveryZone.find(params[:id]).destroy
        redirect_to admin_delivery_zones_url
    end

    private

    def delivery_zone_params
        params.require(:delivery_zone).permit(:name)
    end
end
  

app/views/admin/delivery_zones/edit.haml
%h1.text-center Edit Delivery Zone

= form_for @delivery_zone, url: {:action => "update", :id => @delivery_zone}, html: { method: :put } do |f|
  %p
    = f.label :name
    = f.text_field :name, class: 'form-control'
  %p
    = f.submit "Save", class: 'btn btn-primary'
    = link_to("Cancel", admin_delivery_zone_path(@delivery_zone), class: "btn btn-default text-black")

app/views/admin/delivery_zones/index.haml
%h1.text-center.bd-title Delivery Zones
.table-container
  %table.table.table-condensed.borderless
    %thead
      %tr
        %th ID
        %th Name
    %tbody
      - @delivery_zones.each_with_index do |delivery_zone, index|
        %tr
          %td= delivery_zone.id
          %td= link_to(delivery_zone.name, admin_delivery_zone_path(delivery_zone.id))

= link_to("Add Delivery Zone", new_admin_delivery_zone_path, class: "btn btn-success text-white")

app/views/admin/delivery_zones/new.haml
%h1.text-center New Delivery Zone

= form_for @delivery_zone, url: {:action => "create"}, html: { method: :post } do |f|
  %p
    = f.label :name
    = f.text_field :name, class: 'form-control'
  %p
    = f.submit "Create", class: 'btn btn-primary'

app/views/admin/delivery_zones/show.haml
%h1.text-center Delivery Zone

%h2= @delivery_zone.name

%hr

= link_to("Edit #{@delivery_zone.name}", edit_admin_delivery_zone_path(@delivery_zone.id), class: "btn btn-info text-white")

= link_to("Delete #{@delivery_zone.name}", admin_delivery_zone_path(@delivery_zone.id), method: :delete, class: "btn btn-danger text-white", data: { confirm: "Are you sure you wish to delete?" })

= link_to("All Delivery Zones", admin_delivery_zones_path, class: "float-right")