config/routes.rb
Rails.application.routes.draw do

    root to: redirect('/admin/assignments')

    namespace :admin do
        get "assignments/generate" => "assignments#generate"
        resources :assignments
        resources :delivery_zones
        resources :restaurants do
            resources :meals
            resources :restrict_restaurant_days
            resources :restrict_restaurant_delivery_zones
        end
    end

    namespace :v1 do
        resources :assignments, only: [:index], defaults: { format: :json }
    end
end

app/models/meal.rb
##
# This class represents the a meal.
#
# == Schema Information
#
# Table name: meals
#
#  id            :integer          not null, primary key
#  name          :string
#  restaurant_id :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Meal < ApplicationRecord
    belongs_to :restaurant
end

app/controllers/admin/meals_controller.rb
class Admin::MealsController < ApplicationController

    def new
        @restaurant = Restaurant.find(params[:restaurant_id])
        @meal = @restaurant.meals.build
    end

    def create
        @restaurant = Restaurant.find(params[:restaurant_id])
        @meal = @restaurant.meals.build(meal_params)
        
        @meal = Meal.new(meal_params)
        if @meal.save
            redirect_to admin_restaurant_url(@meal.restaurant)
        else
            render 'new'
        end
    end

    def index
        @meals = Meal.all.order(:name)
    end
  
    def show
        @meal = Meal.find(params[:id])
    end

    def edit
        @meal = Meal.find(params[:id])
        redirect_to admin_restaurants_url if @meal.nil?
    end

    def update
        @meal = Meal.find(params[:id])
        if @meal.update_attributes(meal_params)
            render 'show'
        else
            render 'edit'
        end
    end

    def destroy
        Meal.find(params[:id]).destroy
        flash[:success] = "Meal deleted"
        redirect_to admin_meals_url
    end

    private

    def meal_params
        params.require(:meal).permit(:name, :restaurant_id)
    end
end
  

app/views/admin/meals/edit.haml
%h1.text-center Edit Meal

= form_for @meal, url: {:action => "update", :id => @meal}, html: { method: :put } do |f|
  %p
    = f.label :name
    = f.text_field :name, class: 'form-control'
  %p
    = f.submit "Save", class: 'btn btn-primary'
    = link_to("Cancel", admin_restaurant_path(@meal.restaurant), class: "btn btn-default text-black")

app/views/admin/meals/index.haml
%h1.text-center Meals
.table-container
  %table.table.table-condensed.borderless
    %thead
      %tr
        %th ID
        %th Name
        %th Restaurant
    %tbody
      - @meals.each_with_index do |meal, index|
        %tr
          %td= meal.id
          %td= link_to(meal.restaurant.name, admin_restaurant_path(meal.restaurant_id))
          %td= link_to(meal.name, admin_restaurant_meal_path(meal.id))

app/views/admin/meals/new.haml
%h1.text-center= "New Meal at #{@restaurant.name}"

= form_for @meal, url: admin_restaurant_meals_path(@restaurant), html: { method: :post } do |f|
  %p
    = f.label :name
    = f.text_field :name, class: 'form-control'
    = f.hidden_field :restaurant_id
  %p
    = f.submit "Create", class: 'btn btn-primary'
    = link_to("Cancel", admin_restaurant_path(@restaurant), class: "btn btn-default text-black")

app/views/admin/meals/show.haml
%h1.text-center Meal

%h2= @meal.name


%hr

= link_to("Edit #{@meal.name}", edit_admin_restaurant_meal_path(@meal.id), class: "btn btn-info text-white")

= link_to("Delete #{@meal.name}", admin_restaurant_meal_path(@meal.id), method: :delete, class: "btn btn-danger text-white", data: { confirm: "Are you sure you wish to delete?" })

= link_to(@meal.restaurant.name, admin_restaurant_path(@meal.restaurant.id), class: "float-right")