config/routes.rb
Rails.application.routes.draw do

    root to: redirect('/admin/assignments')

    namespace :admin do
        get "assignments/generate" => "assignments#generate"
        resources :assignments
        resources :delivery_zones
        resources :restaurants do
            resources :meals
            resources :restrict_restaurant_days
            resources :restrict_restaurant_delivery_zones
        end
    end

    namespace :v1 do
        resources :assignments, only: [:index], defaults: { format: :json }
    end
end

app/views/layouts/_nav.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container
    .navbar-header
      %a.navbar-brand= link_to("Chowbus", "/")
    %ul.nav.navbar-nav.navbar-right
      %li.nav-item 
        = link_to("Delivery Assignments", admin_assignments_path, class: "nav-link") 
      %li.nav-item 
        = link_to("Delivery Zones", admin_delivery_zones_path, class: "nav-link") 
      %li.nav-item 
        = link_to("Restaurants", admin_restaurants_path, class: "nav-link") 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chowbus</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>

  <body>
    
    <%= render 'layouts/nav' %>
    <div class="container">
        <%= yield %>
    </div>

  </body>
</html>